server:
  port: 8080

spring:
  profiles:
    # 默认激活 dev 环境
    active: dev

jwt:
  # 签发人
  issuer: wx
  # 秘钥
  secret: kRlaY3u5D6JxfTAII4FCGr5ewYs/+U/gERq4hj7tSfwksbLildz82cIV60S493uPLr/qYY/vMjuii1ZHxYy0Vw==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer